// <auto-generated />
using Caching.InMemory.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Caching.InMemory.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230531064959_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Caching.InMemory.Model.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            ProductDescription = "Monitor Samsung 17 Inch",
                            ProductName = "Monitor",
                            Stock = 10
                        },
                        new
                        {
                            ProductId = 2,
                            ProductDescription = "Monitor Samsung 15 Inch",
                            ProductName = "Monitor",
                            Stock = 10
                        },
                        new
                        {
                            ProductId = 3,
                            ProductDescription = "Monitor Samsung 27 Inch",
                            ProductName = "Monitor",
                            Stock = 10
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
